language: python
python:
  - "3.5"
# command to install dependencies
install:
  - pip install -r requirements.txt

script:
  nosetests --with-coverage --cover-package=tests && coverage report
env:
  - FLASK_VERSION=0.10.1
